#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiFaceRec
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLyChungCu")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDANCU(DANCU instance);
    partial void UpdateDANCU(DANCU instance);
    partial void DeleteDANCU(DANCU instance);
    partial void InsertPHONG(PHONG instance);
    partial void UpdatePHONG(PHONG instance);
    partial void DeletePHONG(PHONG instance);
    partial void InsertRAVAO_HINH(RAVAO_HINH instance);
    partial void UpdateRAVAO_HINH(RAVAO_HINH instance);
    partial void DeleteRAVAO_HINH(RAVAO_HINH instance);
    partial void InsertRAVAO_LAMAT(RAVAO_LAMAT instance);
    partial void UpdateRAVAO_LAMAT(RAVAO_LAMAT instance);
    partial void DeleteRAVAO_LAMAT(RAVAO_LAMAT instance);
    partial void InsertRAVAO_LICHSU(RAVAO_LICHSU instance);
    partial void UpdateRAVAO_LICHSU(RAVAO_LICHSU instance);
    partial void DeleteRAVAO_LICHSU(RAVAO_LICHSU instance);
    partial void InsertRAVAO_TAIKHOAN(RAVAO_TAIKHOAN instance);
    partial void UpdateRAVAO_TAIKHOAN(RAVAO_TAIKHOAN instance);
    partial void DeleteRAVAO_TAIKHOAN(RAVAO_TAIKHOAN instance);
    partial void InsertRAVAO_THOILUONG(RAVAO_THOILUONG instance);
    partial void UpdateRAVAO_THOILUONG(RAVAO_THOILUONG instance);
    partial void DeleteRAVAO_THOILUONG(RAVAO_THOILUONG instance);
    partial void InsertRAVAO_TRANGTHAICAMERA(RAVAO_TRANGTHAICAMERA instance);
    partial void UpdateRAVAO_TRANGTHAICAMERA(RAVAO_TRANGTHAICAMERA instance);
    partial void DeleteRAVAO_TRANGTHAICAMERA(RAVAO_TRANGTHAICAMERA instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::MultiFaceRec.Properties.Settings.Default.QLyChungCuConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DANCU> DANCUs
		{
			get
			{
				return this.GetTable<DANCU>();
			}
		}
		
		public System.Data.Linq.Table<PHONG> PHONGs
		{
			get
			{
				return this.GetTable<PHONG>();
			}
		}
		
		public System.Data.Linq.Table<RAVAO_HINH> RAVAO_HINHs
		{
			get
			{
				return this.GetTable<RAVAO_HINH>();
			}
		}
		
		public System.Data.Linq.Table<RAVAO_LAMAT> RAVAO_LAMATs
		{
			get
			{
				return this.GetTable<RAVAO_LAMAT>();
			}
		}
		
		public System.Data.Linq.Table<RAVAO_LICHSU> RAVAO_LICHSUs
		{
			get
			{
				return this.GetTable<RAVAO_LICHSU>();
			}
		}
		
		public System.Data.Linq.Table<RAVAO_TAIKHOAN> RAVAO_TAIKHOANs
		{
			get
			{
				return this.GetTable<RAVAO_TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<RAVAO_THOILUONG> RAVAO_THOILUONGs
		{
			get
			{
				return this.GetTable<RAVAO_THOILUONG>();
			}
		}
		
		public System.Data.Linq.Table<RAVAO_TRANGTHAICAMERA> RAVAO_TRANGTHAICAMERAs
		{
			get
			{
				return this.GetTable<RAVAO_TRANGTHAICAMERA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANCU")]
	public partial class DANCU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADCU;
		
		private string _CMND;
		
		private string _TENCUDAN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _NOISINH;
		
		private string _QUEQUAN;
		
		private string _SDT;
		
		private string _DANTOC;
		
		private string _QUOCTICH;
		
		private string _NOITHUONGTRU;
		
		private System.Nullable<System.DateTime> _NGAYCAP;
		
		private string _NOICAP;
		
		private string _TIENGDANTOC;
		
		private string _NGHENGHIEP;
		
		private string _EMAIL;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private string _VAITRO;
		
		private string _MAPHONG;
		
		private string _NOILAMVIEC;
		
		private EntitySet<RAVAO_HINH> _RAVAO_HINHs;
		
		private EntitySet<RAVAO_LICHSU> _RAVAO_LICHSUs;
		
		private EntitySet<RAVAO_THOILUONG> _RAVAO_THOILUONGs;
		
		private EntityRef<PHONG> _PHONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADCUChanging(string value);
    partial void OnMADCUChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnTENCUDANChanging(string value);
    partial void OnTENCUDANChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNOISINHChanging(string value);
    partial void OnNOISINHChanged();
    partial void OnQUEQUANChanging(string value);
    partial void OnQUEQUANChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDANTOCChanging(string value);
    partial void OnDANTOCChanged();
    partial void OnQUOCTICHChanging(string value);
    partial void OnQUOCTICHChanged();
    partial void OnNOITHUONGTRUChanging(string value);
    partial void OnNOITHUONGTRUChanged();
    partial void OnNGAYCAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPChanged();
    partial void OnNOICAPChanging(string value);
    partial void OnNOICAPChanged();
    partial void OnTIENGDANTOCChanging(string value);
    partial void OnTIENGDANTOCChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    partial void OnVAITROChanging(string value);
    partial void OnVAITROChanged();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnNOILAMVIECChanging(string value);
    partial void OnNOILAMVIECChanged();
    #endregion
		
		public DANCU()
		{
			this._RAVAO_HINHs = new EntitySet<RAVAO_HINH>(new Action<RAVAO_HINH>(this.attach_RAVAO_HINHs), new Action<RAVAO_HINH>(this.detach_RAVAO_HINHs));
			this._RAVAO_LICHSUs = new EntitySet<RAVAO_LICHSU>(new Action<RAVAO_LICHSU>(this.attach_RAVAO_LICHSUs), new Action<RAVAO_LICHSU>(this.detach_RAVAO_LICHSUs));
			this._RAVAO_THOILUONGs = new EntitySet<RAVAO_THOILUONG>(new Action<RAVAO_THOILUONG>(this.attach_RAVAO_THOILUONGs), new Action<RAVAO_THOILUONG>(this.detach_RAVAO_THOILUONGs));
			this._PHONG = default(EntityRef<PHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADCU", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADCU
		{
			get
			{
				return this._MADCU;
			}
			set
			{
				if ((this._MADCU != value))
				{
					this.OnMADCUChanging(value);
					this.SendPropertyChanging();
					this._MADCU = value;
					this.SendPropertyChanged("MADCU");
					this.OnMADCUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCUDAN", DbType="NVarChar(50)")]
		public string TENCUDAN
		{
			get
			{
				return this._TENCUDAN;
			}
			set
			{
				if ((this._TENCUDAN != value))
				{
					this.OnTENCUDANChanging(value);
					this.SendPropertyChanging();
					this._TENCUDAN = value;
					this.SendPropertyChanged("TENCUDAN");
					this.OnTENCUDANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOISINH", DbType="NVarChar(50)")]
		public string NOISINH
		{
			get
			{
				return this._NOISINH;
			}
			set
			{
				if ((this._NOISINH != value))
				{
					this.OnNOISINHChanging(value);
					this.SendPropertyChanging();
					this._NOISINH = value;
					this.SendPropertyChanged("NOISINH");
					this.OnNOISINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUEQUAN", DbType="NVarChar(100)")]
		public string QUEQUAN
		{
			get
			{
				return this._QUEQUAN;
			}
			set
			{
				if ((this._QUEQUAN != value))
				{
					this.OnQUEQUANChanging(value);
					this.SendPropertyChanging();
					this._QUEQUAN = value;
					this.SendPropertyChanged("QUEQUAN");
					this.OnQUEQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANTOC", DbType="NVarChar(20)")]
		public string DANTOC
		{
			get
			{
				return this._DANTOC;
			}
			set
			{
				if ((this._DANTOC != value))
				{
					this.OnDANTOCChanging(value);
					this.SendPropertyChanging();
					this._DANTOC = value;
					this.SendPropertyChanged("DANTOC");
					this.OnDANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOCTICH", DbType="NVarChar(20)")]
		public string QUOCTICH
		{
			get
			{
				return this._QUOCTICH;
			}
			set
			{
				if ((this._QUOCTICH != value))
				{
					this.OnQUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._QUOCTICH = value;
					this.SendPropertyChanged("QUOCTICH");
					this.OnQUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOITHUONGTRU", DbType="NVarChar(100)")]
		public string NOITHUONGTRU
		{
			get
			{
				return this._NOITHUONGTRU;
			}
			set
			{
				if ((this._NOITHUONGTRU != value))
				{
					this.OnNOITHUONGTRUChanging(value);
					this.SendPropertyChanging();
					this._NOITHUONGTRU = value;
					this.SendPropertyChanged("NOITHUONGTRU");
					this.OnNOITHUONGTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICAP", DbType="NVarChar(50)")]
		public string NOICAP
		{
			get
			{
				return this._NOICAP;
			}
			set
			{
				if ((this._NOICAP != value))
				{
					this.OnNOICAPChanging(value);
					this.SendPropertyChanging();
					this._NOICAP = value;
					this.SendPropertyChanged("NOICAP");
					this.OnNOICAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENGDANTOC", DbType="NVarChar(20)")]
		public string TIENGDANTOC
		{
			get
			{
				return this._TIENGDANTOC;
			}
			set
			{
				if ((this._TIENGDANTOC != value))
				{
					this.OnTIENGDANTOCChanging(value);
					this.SendPropertyChanging();
					this._TIENGDANTOC = value;
					this.SendPropertyChanged("TIENGDANTOC");
					this.OnTIENGDANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="NVarChar(50)")]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAITRO", DbType="NVarChar(50)")]
		public string VAITRO
		{
			get
			{
				return this._VAITRO;
			}
			set
			{
				if ((this._VAITRO != value))
				{
					this.OnVAITROChanging(value);
					this.SendPropertyChanging();
					this._VAITRO = value;
					this.SendPropertyChanged("VAITRO");
					this.OnVAITROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="NVarChar(30)")]
		public string MAPHONG
		{
			get
			{
				return this._MAPHONG;
			}
			set
			{
				if ((this._MAPHONG != value))
				{
					if (this._PHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHONGChanging(value);
					this.SendPropertyChanging();
					this._MAPHONG = value;
					this.SendPropertyChanged("MAPHONG");
					this.OnMAPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOILAMVIEC", DbType="NVarChar(100)")]
		public string NOILAMVIEC
		{
			get
			{
				return this._NOILAMVIEC;
			}
			set
			{
				if ((this._NOILAMVIEC != value))
				{
					this.OnNOILAMVIECChanging(value);
					this.SendPropertyChanging();
					this._NOILAMVIEC = value;
					this.SendPropertyChanged("NOILAMVIEC");
					this.OnNOILAMVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANCU_RAVAO_HINH", Storage="_RAVAO_HINHs", ThisKey="MADCU", OtherKey="IDDANCU")]
		public EntitySet<RAVAO_HINH> RAVAO_HINHs
		{
			get
			{
				return this._RAVAO_HINHs;
			}
			set
			{
				this._RAVAO_HINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANCU_RAVAO_LICHSU", Storage="_RAVAO_LICHSUs", ThisKey="MADCU", OtherKey="IDDANCU")]
		public EntitySet<RAVAO_LICHSU> RAVAO_LICHSUs
		{
			get
			{
				return this._RAVAO_LICHSUs;
			}
			set
			{
				this._RAVAO_LICHSUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANCU_RAVAO_THOILUONG", Storage="_RAVAO_THOILUONGs", ThisKey="MADCU", OtherKey="ID_DANCU")]
		public EntitySet<RAVAO_THOILUONG> RAVAO_THOILUONGs
		{
			get
			{
				return this._RAVAO_THOILUONGs;
			}
			set
			{
				this._RAVAO_THOILUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_DANCU", Storage="_PHONG", ThisKey="MAPHONG", OtherKey="MAPHONG", IsForeignKey=true)]
		public PHONG PHONG
		{
			get
			{
				return this._PHONG.Entity;
			}
			set
			{
				PHONG previousValue = this._PHONG.Entity;
				if (((previousValue != value) 
							|| (this._PHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG.Entity = null;
						previousValue.DANCUs.Remove(this);
					}
					this._PHONG.Entity = value;
					if ((value != null))
					{
						value.DANCUs.Add(this);
						this._MAPHONG = value.MAPHONG;
					}
					else
					{
						this._MAPHONG = default(string);
					}
					this.SendPropertyChanged("PHONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RAVAO_HINHs(RAVAO_HINH entity)
		{
			this.SendPropertyChanging();
			entity.DANCU = this;
		}
		
		private void detach_RAVAO_HINHs(RAVAO_HINH entity)
		{
			this.SendPropertyChanging();
			entity.DANCU = null;
		}
		
		private void attach_RAVAO_LICHSUs(RAVAO_LICHSU entity)
		{
			this.SendPropertyChanging();
			entity.DANCU = this;
		}
		
		private void detach_RAVAO_LICHSUs(RAVAO_LICHSU entity)
		{
			this.SendPropertyChanging();
			entity.DANCU = null;
		}
		
		private void attach_RAVAO_THOILUONGs(RAVAO_THOILUONG entity)
		{
			this.SendPropertyChanging();
			entity.DANCU = this;
		}
		
		private void detach_RAVAO_THOILUONGs(RAVAO_THOILUONG entity)
		{
			this.SendPropertyChanging();
			entity.DANCU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONG")]
	public partial class PHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHONG;
		
		private System.Nullable<int> _GIAPHONG;
		
		private string _SONGUOI;
		
		private string _TINHTRANGPHONG;
		
		private string _MATB;
		
		private string _MASUCO;
		
		private string _MATK;
		
		private string _MACN;
		
		private string _SOPHONG;
		
		private EntitySet<DANCU> _DANCUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnGIAPHONGChanging(System.Nullable<int> value);
    partial void OnGIAPHONGChanged();
    partial void OnSONGUOIChanging(string value);
    partial void OnSONGUOIChanged();
    partial void OnTINHTRANGPHONGChanging(string value);
    partial void OnTINHTRANGPHONGChanged();
    partial void OnMATBChanging(string value);
    partial void OnMATBChanged();
    partial void OnMASUCOChanging(string value);
    partial void OnMASUCOChanged();
    partial void OnMATKChanging(string value);
    partial void OnMATKChanged();
    partial void OnMACNChanging(string value);
    partial void OnMACNChanged();
    partial void OnSOPHONGChanging(string value);
    partial void OnSOPHONGChanged();
    #endregion
		
		public PHONG()
		{
			this._DANCUs = new EntitySet<DANCU>(new Action<DANCU>(this.attach_DANCUs), new Action<DANCU>(this.detach_DANCUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHONG
		{
			get
			{
				return this._MAPHONG;
			}
			set
			{
				if ((this._MAPHONG != value))
				{
					this.OnMAPHONGChanging(value);
					this.SendPropertyChanging();
					this._MAPHONG = value;
					this.SendPropertyChanged("MAPHONG");
					this.OnMAPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAPHONG", DbType="Int")]
		public System.Nullable<int> GIAPHONG
		{
			get
			{
				return this._GIAPHONG;
			}
			set
			{
				if ((this._GIAPHONG != value))
				{
					this.OnGIAPHONGChanging(value);
					this.SendPropertyChanging();
					this._GIAPHONG = value;
					this.SendPropertyChanged("GIAPHONG");
					this.OnGIAPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGUOI", DbType="NVarChar(10)")]
		public string SONGUOI
		{
			get
			{
				return this._SONGUOI;
			}
			set
			{
				if ((this._SONGUOI != value))
				{
					this.OnSONGUOIChanging(value);
					this.SendPropertyChanging();
					this._SONGUOI = value;
					this.SendPropertyChanged("SONGUOI");
					this.OnSONGUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANGPHONG", DbType="NVarChar(50)")]
		public string TINHTRANGPHONG
		{
			get
			{
				return this._TINHTRANGPHONG;
			}
			set
			{
				if ((this._TINHTRANGPHONG != value))
				{
					this.OnTINHTRANGPHONGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANGPHONG = value;
					this.SendPropertyChanged("TINHTRANGPHONG");
					this.OnTINHTRANGPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATB", DbType="NVarChar(10)")]
		public string MATB
		{
			get
			{
				return this._MATB;
			}
			set
			{
				if ((this._MATB != value))
				{
					this.OnMATBChanging(value);
					this.SendPropertyChanging();
					this._MATB = value;
					this.SendPropertyChanged("MATB");
					this.OnMATBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASUCO", DbType="NVarChar(10)")]
		public string MASUCO
		{
			get
			{
				return this._MASUCO;
			}
			set
			{
				if ((this._MASUCO != value))
				{
					this.OnMASUCOChanging(value);
					this.SendPropertyChanging();
					this._MASUCO = value;
					this.SendPropertyChanged("MASUCO");
					this.OnMASUCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", DbType="NVarChar(30)")]
		public string MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACN", DbType="NVarChar(10)")]
		public string MACN
		{
			get
			{
				return this._MACN;
			}
			set
			{
				if ((this._MACN != value))
				{
					this.OnMACNChanging(value);
					this.SendPropertyChanging();
					this._MACN = value;
					this.SendPropertyChanged("MACN");
					this.OnMACNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPHONG", DbType="NVarChar(10)")]
		public string SOPHONG
		{
			get
			{
				return this._SOPHONG;
			}
			set
			{
				if ((this._SOPHONG != value))
				{
					this.OnSOPHONGChanging(value);
					this.SendPropertyChanging();
					this._SOPHONG = value;
					this.SendPropertyChanged("SOPHONG");
					this.OnSOPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_DANCU", Storage="_DANCUs", ThisKey="MAPHONG", OtherKey="MAPHONG")]
		public EntitySet<DANCU> DANCUs
		{
			get
			{
				return this._DANCUs;
			}
			set
			{
				this._DANCUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANCUs(DANCU entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = this;
		}
		
		private void detach_DANCUs(DANCU entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAVAO_HINH")]
	public partial class RAVAO_HINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHINH;
		
		private string _IDDANCU;
		
		private string _TENHINH;
		
		private EntityRef<DANCU> _DANCU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHINHChanging(int value);
    partial void OnIDHINHChanged();
    partial void OnIDDANCUChanging(string value);
    partial void OnIDDANCUChanged();
    partial void OnTENHINHChanging(string value);
    partial void OnTENHINHChanged();
    #endregion
		
		public RAVAO_HINH()
		{
			this._DANCU = default(EntityRef<DANCU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHINH
		{
			get
			{
				return this._IDHINH;
			}
			set
			{
				if ((this._IDHINH != value))
				{
					this.OnIDHINHChanging(value);
					this.SendPropertyChanging();
					this._IDHINH = value;
					this.SendPropertyChanged("IDHINH");
					this.OnIDHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDANCU", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDANCU
		{
			get
			{
				return this._IDDANCU;
			}
			set
			{
				if ((this._IDDANCU != value))
				{
					if (this._DANCU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDANCUChanging(value);
					this.SendPropertyChanging();
					this._IDDANCU = value;
					this.SendPropertyChanged("IDDANCU");
					this.OnIDDANCUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHINH", DbType="VarChar(50)")]
		public string TENHINH
		{
			get
			{
				return this._TENHINH;
			}
			set
			{
				if ((this._TENHINH != value))
				{
					this.OnTENHINHChanging(value);
					this.SendPropertyChanging();
					this._TENHINH = value;
					this.SendPropertyChanged("TENHINH");
					this.OnTENHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANCU_RAVAO_HINH", Storage="_DANCU", ThisKey="IDDANCU", OtherKey="MADCU", IsForeignKey=true)]
		public DANCU DANCU
		{
			get
			{
				return this._DANCU.Entity;
			}
			set
			{
				DANCU previousValue = this._DANCU.Entity;
				if (((previousValue != value) 
							|| (this._DANCU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANCU.Entity = null;
						previousValue.RAVAO_HINHs.Remove(this);
					}
					this._DANCU.Entity = value;
					if ((value != null))
					{
						value.RAVAO_HINHs.Add(this);
						this._IDDANCU = value.MADCU;
					}
					else
					{
						this._IDDANCU = default(string);
					}
					this.SendPropertyChanged("DANCU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAVAO_LAMAT")]
	public partial class RAVAO_LAMAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LAMAT;
		
		private string _HINH;
		
		private string _CAMERA;
		
		private string _THOIDIEM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LAMATChanging(int value);
    partial void OnID_LAMATChanged();
    partial void OnHINHChanging(string value);
    partial void OnHINHChanged();
    partial void OnCAMERAChanging(string value);
    partial void OnCAMERAChanged();
    partial void OnTHOIDIEMChanging(string value);
    partial void OnTHOIDIEMChanged();
    #endregion
		
		public RAVAO_LAMAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LAMAT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LAMAT
		{
			get
			{
				return this._ID_LAMAT;
			}
			set
			{
				if ((this._ID_LAMAT != value))
				{
					this.OnID_LAMATChanging(value);
					this.SendPropertyChanging();
					this._ID_LAMAT = value;
					this.SendPropertyChanged("ID_LAMAT");
					this.OnID_LAMATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="VarChar(50)")]
		public string HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAMERA", DbType="NVarChar(10)")]
		public string CAMERA
		{
			get
			{
				return this._CAMERA;
			}
			set
			{
				if ((this._CAMERA != value))
				{
					this.OnCAMERAChanging(value);
					this.SendPropertyChanging();
					this._CAMERA = value;
					this.SendPropertyChanged("CAMERA");
					this.OnCAMERAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIDIEM", DbType="VarChar(50)")]
		public string THOIDIEM
		{
			get
			{
				return this._THOIDIEM;
			}
			set
			{
				if ((this._THOIDIEM != value))
				{
					this.OnTHOIDIEMChanging(value);
					this.SendPropertyChanging();
					this._THOIDIEM = value;
					this.SendPropertyChanged("THOIDIEM");
					this.OnTHOIDIEMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAVAO_LICHSU")]
	public partial class RAVAO_LICHSU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDANCU;
		
		private System.DateTime _THOIGIAN;
		
		private string _CAMERA;
		
		private EntityRef<DANCU> _DANCU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDANCUChanging(string value);
    partial void OnIDDANCUChanged();
    partial void OnTHOIGIANChanging(System.DateTime value);
    partial void OnTHOIGIANChanged();
    partial void OnCAMERAChanging(string value);
    partial void OnCAMERAChanged();
    #endregion
		
		public RAVAO_LICHSU()
		{
			this._DANCU = default(EntityRef<DANCU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDANCU", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDANCU
		{
			get
			{
				return this._IDDANCU;
			}
			set
			{
				if ((this._IDDANCU != value))
				{
					if (this._DANCU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDANCUChanging(value);
					this.SendPropertyChanging();
					this._IDDANCU = value;
					this.SendPropertyChanged("IDDANCU");
					this.OnIDDANCUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime THOIGIAN
		{
			get
			{
				return this._THOIGIAN;
			}
			set
			{
				if ((this._THOIGIAN != value))
				{
					this.OnTHOIGIANChanging(value);
					this.SendPropertyChanging();
					this._THOIGIAN = value;
					this.SendPropertyChanged("THOIGIAN");
					this.OnTHOIGIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAMERA", DbType="NVarChar(10)")]
		public string CAMERA
		{
			get
			{
				return this._CAMERA;
			}
			set
			{
				if ((this._CAMERA != value))
				{
					this.OnCAMERAChanging(value);
					this.SendPropertyChanging();
					this._CAMERA = value;
					this.SendPropertyChanged("CAMERA");
					this.OnCAMERAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANCU_RAVAO_LICHSU", Storage="_DANCU", ThisKey="IDDANCU", OtherKey="MADCU", IsForeignKey=true)]
		public DANCU DANCU
		{
			get
			{
				return this._DANCU.Entity;
			}
			set
			{
				DANCU previousValue = this._DANCU.Entity;
				if (((previousValue != value) 
							|| (this._DANCU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANCU.Entity = null;
						previousValue.RAVAO_LICHSUs.Remove(this);
					}
					this._DANCU.Entity = value;
					if ((value != null))
					{
						value.RAVAO_LICHSUs.Add(this);
						this._IDDANCU = value.MADCU;
					}
					else
					{
						this._IDDANCU = default(string);
					}
					this.SendPropertyChanged("DANCU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAVAO_TAIKHOAN")]
	public partial class RAVAO_TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDN;
		
		private string _MATKHAU;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _CMND;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private string _CHUCVU;
		
		private string _QUYEN;
		
		private System.Data.Linq.Binary _HINHANH;
		
		private EntitySet<RAVAO_TRANGTHAICAMERA> _RAVAO_TRANGTHAICAMERAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnQUYENChanging(string value);
    partial void OnQUYENChanged();
    partial void OnHINHANHChanging(System.Data.Linq.Binary value);
    partial void OnHINHANHChanged();
    #endregion
		
		public RAVAO_TAIKHOAN()
		{
			this._RAVAO_TRANGTHAICAMERAs = new EntitySet<RAVAO_TRANGTHAICAMERA>(new Action<RAVAO_TRANGTHAICAMERA>(this.attach_RAVAO_TRANGTHAICAMERAs), new Action<RAVAO_TRANGTHAICAMERA>(this.detach_RAVAO_TRANGTHAICAMERAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(100)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(100)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(30)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(150)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(50)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="NVarChar(30)")]
		public string QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAVAO_TAIKHOAN_RAVAO_TRANGTHAICAMERA", Storage="_RAVAO_TRANGTHAICAMERAs", ThisKey="TENDN", OtherKey="TAIKHOAN")]
		public EntitySet<RAVAO_TRANGTHAICAMERA> RAVAO_TRANGTHAICAMERAs
		{
			get
			{
				return this._RAVAO_TRANGTHAICAMERAs;
			}
			set
			{
				this._RAVAO_TRANGTHAICAMERAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RAVAO_TRANGTHAICAMERAs(RAVAO_TRANGTHAICAMERA entity)
		{
			this.SendPropertyChanging();
			entity.RAVAO_TAIKHOAN = this;
		}
		
		private void detach_RAVAO_TRANGTHAICAMERAs(RAVAO_TRANGTHAICAMERA entity)
		{
			this.SendPropertyChanging();
			entity.RAVAO_TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAVAO_THOILUONG")]
	public partial class RAVAO_THOILUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_THOILUONG;
		
		private string _ID_DANCU;
		
		private System.DateTime _NGAYHIENTAI;
		
		private System.Nullable<System.TimeSpan> _GIORA;
		
		private System.Nullable<System.TimeSpan> _GIOVAO;
		
		private System.Nullable<int> _LANTHU;
		
		private EntityRef<DANCU> _DANCU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_THOILUONGChanging(int value);
    partial void OnID_THOILUONGChanged();
    partial void OnID_DANCUChanging(string value);
    partial void OnID_DANCUChanged();
    partial void OnNGAYHIENTAIChanging(System.DateTime value);
    partial void OnNGAYHIENTAIChanged();
    partial void OnGIORAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGIORAChanged();
    partial void OnGIOVAOChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGIOVAOChanged();
    partial void OnLANTHUChanging(System.Nullable<int> value);
    partial void OnLANTHUChanged();
    #endregion
		
		public RAVAO_THOILUONG()
		{
			this._DANCU = default(EntityRef<DANCU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THOILUONG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_THOILUONG
		{
			get
			{
				return this._ID_THOILUONG;
			}
			set
			{
				if ((this._ID_THOILUONG != value))
				{
					this.OnID_THOILUONGChanging(value);
					this.SendPropertyChanging();
					this._ID_THOILUONG = value;
					this.SendPropertyChanged("ID_THOILUONG");
					this.OnID_THOILUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DANCU", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_DANCU
		{
			get
			{
				return this._ID_DANCU;
			}
			set
			{
				if ((this._ID_DANCU != value))
				{
					if (this._DANCU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DANCUChanging(value);
					this.SendPropertyChanging();
					this._ID_DANCU = value;
					this.SendPropertyChanged("ID_DANCU");
					this.OnID_DANCUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHIENTAI", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NGAYHIENTAI
		{
			get
			{
				return this._NGAYHIENTAI;
			}
			set
			{
				if ((this._NGAYHIENTAI != value))
				{
					this.OnNGAYHIENTAIChanging(value);
					this.SendPropertyChanging();
					this._NGAYHIENTAI = value;
					this.SendPropertyChanged("NGAYHIENTAI");
					this.OnNGAYHIENTAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIORA", DbType="Time")]
		public System.Nullable<System.TimeSpan> GIORA
		{
			get
			{
				return this._GIORA;
			}
			set
			{
				if ((this._GIORA != value))
				{
					this.OnGIORAChanging(value);
					this.SendPropertyChanging();
					this._GIORA = value;
					this.SendPropertyChanged("GIORA");
					this.OnGIORAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOVAO", DbType="Time")]
		public System.Nullable<System.TimeSpan> GIOVAO
		{
			get
			{
				return this._GIOVAO;
			}
			set
			{
				if ((this._GIOVAO != value))
				{
					this.OnGIOVAOChanging(value);
					this.SendPropertyChanging();
					this._GIOVAO = value;
					this.SendPropertyChanged("GIOVAO");
					this.OnGIOVAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANTHU", DbType="Int")]
		public System.Nullable<int> LANTHU
		{
			get
			{
				return this._LANTHU;
			}
			set
			{
				if ((this._LANTHU != value))
				{
					this.OnLANTHUChanging(value);
					this.SendPropertyChanging();
					this._LANTHU = value;
					this.SendPropertyChanged("LANTHU");
					this.OnLANTHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANCU_RAVAO_THOILUONG", Storage="_DANCU", ThisKey="ID_DANCU", OtherKey="MADCU", IsForeignKey=true)]
		public DANCU DANCU
		{
			get
			{
				return this._DANCU.Entity;
			}
			set
			{
				DANCU previousValue = this._DANCU.Entity;
				if (((previousValue != value) 
							|| (this._DANCU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANCU.Entity = null;
						previousValue.RAVAO_THOILUONGs.Remove(this);
					}
					this._DANCU.Entity = value;
					if ((value != null))
					{
						value.RAVAO_THOILUONGs.Add(this);
						this._ID_DANCU = value.MADCU;
					}
					else
					{
						this._ID_DANCU = default(string);
					}
					this.SendPropertyChanged("DANCU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAVAO_TRANGTHAICAMERA")]
	public partial class RAVAO_TRANGTHAICAMERA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TAIKHOAN;
		
		private string _TEN_NUT;
		
		private System.Nullable<int> _TRANGTHAI;
		
		private EntityRef<RAVAO_TAIKHOAN> _RAVAO_TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTAIKHOANChanging(string value);
    partial void OnTAIKHOANChanged();
    partial void OnTEN_NUTChanging(string value);
    partial void OnTEN_NUTChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<int> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public RAVAO_TRANGTHAICAMERA()
		{
			this._RAVAO_TAIKHOAN = default(EntityRef<RAVAO_TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN", DbType="Char(50)")]
		public string TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN;
			}
			set
			{
				if ((this._TAIKHOAN != value))
				{
					if (this._RAVAO_TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN = value;
					this.SendPropertyChanged("TAIKHOAN");
					this.OnTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NUT", DbType="NVarChar(30)")]
		public string TEN_NUT
		{
			get
			{
				return this._TEN_NUT;
			}
			set
			{
				if ((this._TEN_NUT != value))
				{
					this.OnTEN_NUTChanging(value);
					this.SendPropertyChanging();
					this._TEN_NUT = value;
					this.SendPropertyChanged("TEN_NUT");
					this.OnTEN_NUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Int")]
		public System.Nullable<int> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAVAO_TAIKHOAN_RAVAO_TRANGTHAICAMERA", Storage="_RAVAO_TAIKHOAN", ThisKey="TAIKHOAN", OtherKey="TENDN", IsForeignKey=true)]
		public RAVAO_TAIKHOAN RAVAO_TAIKHOAN
		{
			get
			{
				return this._RAVAO_TAIKHOAN.Entity;
			}
			set
			{
				RAVAO_TAIKHOAN previousValue = this._RAVAO_TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._RAVAO_TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RAVAO_TAIKHOAN.Entity = null;
						previousValue.RAVAO_TRANGTHAICAMERAs.Remove(this);
					}
					this._RAVAO_TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.RAVAO_TRANGTHAICAMERAs.Add(this);
						this._TAIKHOAN = value.TENDN;
					}
					else
					{
						this._TAIKHOAN = default(string);
					}
					this.SendPropertyChanged("RAVAO_TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
